/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWeeklyRecapRouteImport } from './routes/_authenticated/weekly-recap'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedBriefingRouteImport } from './routes/_authenticated/briefing'
import { Route as AuthenticatedBriefingIdRouteImport } from './routes/_authenticated/briefing.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksWeeklyRecapRouteImport } from './routes/api/public/hooks/weekly-recap'
import { Route as ApiPublicHooksIngestBriefingsRouteImport } from './routes/api/public/hooks/ingest-briefings'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeeklyRecapRoute =
  AuthenticatedWeeklyRecapRouteImport.update({
    id: '/weekly-recap',
    path: '/weekly-recap',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBriefingRoute = AuthenticatedBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBriefingIdRoute = AuthenticatedBriefingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBriefingRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklyRecapRoute =
  ApiPublicHooksWeeklyRecapRouteImport.update({
    id: '/api/public/hooks/weekly-recap',
    path: '/api/public/hooks/weekly-recap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIngestBriefingsRoute =
  ApiPublicHooksIngestBriefingsRouteImport.update({
    id: '/api/public/hooks/ingest-briefings',
    path: '/api/public/hooks/ingest-briefings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/briefing': typeof AuthenticatedBriefingRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/weekly-recap': typeof AuthenticatedWeeklyRecapRoute
  '/briefing/$id': typeof AuthenticatedBriefingIdRoute
  '/api/public/hooks/ingest-briefings': typeof ApiPublicHooksIngestBriefingsRoute
  '/api/public/hooks/weekly-recap': typeof ApiPublicHooksWeeklyRecapRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/briefing': typeof AuthenticatedBriefingRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/weekly-recap': typeof AuthenticatedWeeklyRecapRoute
  '/briefing/$id': typeof AuthenticatedBriefingIdRoute
  '/api/public/hooks/ingest-briefings': typeof ApiPublicHooksIngestBriefingsRoute
  '/api/public/hooks/weekly-recap': typeof ApiPublicHooksWeeklyRecapRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/preview': typeof PreviewRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/briefing': typeof AuthenticatedBriefingRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/weekly-recap': typeof AuthenticatedWeeklyRecapRoute
  '/_authenticated/briefing/$id': typeof AuthenticatedBriefingIdRoute
  '/api/public/hooks/ingest-briefings': typeof ApiPublicHooksIngestBriefingsRoute
  '/api/public/hooks/weekly-recap': typeof ApiPublicHooksWeeklyRecapRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/preview'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/briefing'
    | '/onboarding'
    | '/saved'
    | '/settings'
    | '/weekly-recap'
    | '/briefing/$id'
    | '/api/public/hooks/ingest-briefings'
    | '/api/public/hooks/weekly-recap'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/preview'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/briefing'
    | '/onboarding'
    | '/saved'
    | '/settings'
    | '/weekly-recap'
    | '/briefing/$id'
    | '/api/public/hooks/ingest-briefings'
    | '/api/public/hooks/weekly-recap'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/preview'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/_authenticated/briefing'
    | '/_authenticated/onboarding'
    | '/_authenticated/saved'
    | '/_authenticated/settings'
    | '/_authenticated/weekly-recap'
    | '/_authenticated/briefing/$id'
    | '/api/public/hooks/ingest-briefings'
    | '/api/public/hooks/weekly-recap'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PreviewRoute: typeof PreviewRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiPublicHooksIngestBriefingsRoute: typeof ApiPublicHooksIngestBriefingsRoute
  ApiPublicHooksWeeklyRecapRoute: typeof ApiPublicHooksWeeklyRecapRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weekly-recap': {
      id: '/_authenticated/weekly-recap'
      path: '/weekly-recap'
      fullPath: '/weekly-recap'
      preLoaderRoute: typeof AuthenticatedWeeklyRecapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/briefing': {
      id: '/_authenticated/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof AuthenticatedBriefingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/briefing/$id': {
      id: '/_authenticated/briefing/$id'
      path: '/$id'
      fullPath: '/briefing/$id'
      preLoaderRoute: typeof AuthenticatedBriefingIdRouteImport
      parentRoute: typeof AuthenticatedBriefingRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-recap': {
      id: '/api/public/hooks/weekly-recap'
      path: '/api/public/hooks/weekly-recap'
      fullPath: '/api/public/hooks/weekly-recap'
      preLoaderRoute: typeof ApiPublicHooksWeeklyRecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest-briefings': {
      id: '/api/public/hooks/ingest-briefings'
      path: '/api/public/hooks/ingest-briefings'
      fullPath: '/api/public/hooks/ingest-briefings'
      preLoaderRoute: typeof ApiPublicHooksIngestBriefingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedBriefingRouteChildren {
  AuthenticatedBriefingIdRoute: typeof AuthenticatedBriefingIdRoute
}

const AuthenticatedBriefingRouteChildren: AuthenticatedBriefingRouteChildren = {
  AuthenticatedBriefingIdRoute: AuthenticatedBriefingIdRoute,
}

const AuthenticatedBriefingRouteWithChildren =
  AuthenticatedBriefingRoute._addFileChildren(
    AuthenticatedBriefingRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBriefingRoute: typeof AuthenticatedBriefingRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWeeklyRecapRoute: typeof AuthenticatedWeeklyRecapRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBriefingRoute: AuthenticatedBriefingRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWeeklyRecapRoute: AuthenticatedWeeklyRecapRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PreviewRoute: PreviewRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiPublicHooksIngestBriefingsRoute: ApiPublicHooksIngestBriefingsRoute,
  ApiPublicHooksWeeklyRecapRoute: ApiPublicHooksWeeklyRecapRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
